name: "Daily Fudan"

on:
  schedule:
    - cron: "30 2 * * *"  # scheduled at 10:30 (UTC+8) everyday
  workflow_dispatch:

jobs:
  daily_fudan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Random sleep
        if: github.event_name == 'schedule'
        run: sleep $(shuf -i 10-300 -n 1)

      - name: Complete daily_fudan
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python3 ./dailyFudan.py '${{ secrets.UIS }}' '${{ secrets.EMAIL }}'
